### PR TITLE
Add test.py for inferencing

### PR DESCRIPTION
**Pull request by gachiemchiep**

### CODE REVIEW

**Comment by PingoLH** [comment]
Hello, thank you very much for your contribution. Just one thing, the line 118 in validate.py is for replacing the .png extension. After removing this line and the file name will become *.png.jpg which is a little confusing. Do you meet any issue for this line that makes you remove it?

**Comment by gachiemchiep** [comment]
> Hello, thank you very much for your contribution. Just one thing, the line 118 in validate.py is for replacing the .png extension. After removing this line and the file name will become *.png.jpg which is a little confusing. Do you meet any issue for this line that makes you remove it?

Hello @PingoLH  
Some of my files have ".jpeg" extensions. The fname_new = fname_new[:-4] will create a *..jpg. So i remove it. 
Maybe it would better use the os.path.splitext for a correct naming.

**Comment by gachiemchiep** [comment]
Hello @PingoLH 
I revert the change in validate.py

**Comment by PingoLH** [comment]
Thank you very much for your contribution and issue report. I will modify the extension replacement for the issue.

**Pull request merged**
